import { getAllUsers, countUsers } from '../../models/User.js';
import fs from 'fs-extra';
import path from 'path';

export default {
    name: 'exportusers',
    aliases: ['exportlist', 'downloadusers', 'userexport'],
    category: 'owner',
    description: 'Export all users to a text file',
    usage: 'exportusers [format] [filter]',
    example: 'exportusers txt all',
    cooldown: 10,
    permissions: ['owner'],
    ownerOnly: true,

    async execute({ sock, message, args, from, sender }) {
        try {
            const format = args[0]?.toLowerCase() || 'txt';
            const filterType = args[1]?.toLowerCase() || 'all';

            if (!['txt', 'csv', 'json'].includes(format)) {
                return await sock.sendMessage(from, {
                    text: 'Error: Invalid format\n\nSupported formats:\n• txt - Plain text\n• csv - Comma separated\n• json - JSON format\n\nExample: exportusers txt all'
                }, { quoted: message });
            }

            await sock.sendMessage(from, {
                text: `Exporting users...\n\nFormat: ${format.toUpperCase()}\nFilter: ${filterType}\n\nThis may take a moment...`
            }, { quoted: message });

            let filter = {};
            let filterText = 'all users';

            if (filterType === 'premium') {
                filter.isPremium = true;
                filterText = 'premium users';
            } else if (filterType === 'banned') {
                filter.isBanned = true;
                filterText = 'banned users';
            } else if (filterType === 'active') {
                filter['statistics.lastActive'] = { 
                    $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) 
                };
                filterText = 'active users (24h)';
            }

            const totalUsers = await countUsers(filter);
            
            if (totalUsers === 0) {
                return await sock.sendMessage(from, {
                    text: `No Users Found\n\nFilter: ${filterText}\nTotal: 0 users\n\nTry different filter or check database`
                }, { quoted: message });
            }

            const users = await getAllUsers(filter, totalUsers, 0);

            const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19);
            const filename = `users_${filterType}_${timestamp}.${format}`;
            const filepath = path.join(process.cwd(), 'temp', filename);

            await fs.ensureDir(path.join(process.cwd(), 'temp'));

            let content;
            let mimeType;

            if (format === 'txt') {
                content = this.generateTXT(users, filterText);
                mimeType = 'text/plain';
            } else if (format === 'csv') {
                content = this.generateCSV(users);
                mimeType = 'text/csv';
            } else if (format === 'json') {
                content = this.generateJSON(users, filterText);
                mimeType = 'application/json';
            }

            await fs.writeFile(filepath, content, 'utf8');

            const fileStats = await fs.stat(filepath);
            const fileSizeKB = (fileStats.size / 1024).toFixed(2);

            await sock.sendMessage(from, {
                document: { url: filepath },
                mimetype: mimeType,
                fileName: filename,
                caption: `User Export Complete\n\nFormat: ${format.toUpperCase()}\nFilter: ${filterText}\nTotal Users: ${totalUsers}\nFile Size: ${fileSizeKB} KB\nExported: ${new Date().toLocaleString()}\n\nGenerated by: @${sender.split('@')[0]}`,
                mentions: [sender]
            }, { quoted: message });

            setTimeout(async () => {
                try {
                    await fs.remove(filepath);
                } catch (e) {
                    console.error('Failed to delete temp file:', e);
                }
            }, 60000);

        } catch (error) {
            console.error('Export users error:', error);
            
            await sock.sendMessage(from, {
                text: `Export Failed\n\nError: ${error.message}\n\nPossible causes:\n• Database not connected\n• Insufficient permissions\n• Disk space full\n• Query timeout\n\nCheck logs and try again`
            }, { quoted: message });
        }
    },

    generateTXT(users, filterText) {
        let content = `User Export - ${filterText}\n`;
        content += `Generated: ${new Date().toLocaleString()}\n`;
        content += `Total Users: ${users.length}\n`;
        content += `${'='.repeat(80)}\n\n`;

        users.forEach((user, index) => {
            const phone = user.phone || user.jid.split('@')[0];
            const name = user.name || 'Unknown';
            const status = [];
            
            if (user.isPremium) status.push('Premium');
            if (user.isBanned) status.push('Banned');
            
            const statusText = status.length > 0 ? ` [${status.join(', ')}]` : '';
            
            content += `${index + 1}. ${name}${statusText}\n`;
            content += `   JID: ${user.jid}\n`;
            content += `   Phone: +${phone}\n`;
            
            if (user.statistics?.lastActive) {
                content += `   Last Active: ${new Date(user.statistics.lastActive).toLocaleString()}\n`;
            }
            
            if (user.createdAt) {
                content += `   Joined: ${new Date(user.createdAt).toLocaleDateString()}\n`;
            }
            
            content += `\n`;
        });

        content += `${'='.repeat(80)}\n`;
        content += `End of Export - Total: ${users.length} users\n`;

        return content;
    },

    generateCSV(users) {
        let content = 'Number,Name,JID,Phone,Premium,Banned,Last Active,Joined\n';

        users.forEach((user, index) => {
            const phone = user.phone || user.jid.split('@')[0];
            const name = (user.name || 'Unknown').replace(/,/g, ';');
            const isPremium = user.isPremium ? 'Yes' : 'No';
            const isBanned = user.isBanned ? 'Yes' : 'No';
            const lastActive = user.statistics?.lastActive 
                ? new Date(user.statistics.lastActive).toISOString()
                : 'Never';
            const joined = user.createdAt 
                ? new Date(user.createdAt).toISOString()
                : 'Unknown';

            content += `${index + 1},"${name}","${user.jid}","+${phone}","${isPremium}","${isBanned}","${lastActive}","${joined}"\n`;
        });

        return content;
    },

    generateJSON(users, filterText) {
        const exportData = {
            exportInfo: {
                generatedAt: new Date().toISOString(),
                filter: filterText,
                totalUsers: users.length,
                format: 'JSON'
            },
            users: users.map((user, index) => ({
                number: index + 1,
                name: user.name || 'Unknown',
                jid: user.jid,
                phone: user.phone || user.jid.split('@')[0],
                isPremium: user.isPremium || false,
                isBanned: user.isBanned || false,
                lastActive: user.statistics?.lastActive || null,
                joinedAt: user.createdAt || null,
                economy: {
                    balance: user.economy?.balance || 0,
                    level: user.economy?.level || 1
                },
                statistics: {
                    commandsUsed: user.statistics?.commandsUsed || 0,
                    messagesent: user.statistics?.messagesSent || 0
                }
            }))
        };

        return JSON.stringify(exportData, null, 2);
    }
};
