import axios from 'axios';
import config from '../../config.js';

export default {
    name: 'screenshot',
    aliases: ['ss', 'ssweb', 'capture'],
    category: 'downloader',
    description: 'Take screenshot of a website',
    usage: 'screenshot <url>',
    cooldown: 5,
    permissions: ['user'],
    args: true,
    minArgs: 1,
    maxArgs: 2,
    typing: true,
    premium: false,
    hidden: false,
    ownerOnly: false,
    supportsReply: false,
    supportsChat: true,
    supportsReact: true,
    supportsButtons: false,

    async execute({ sock, message, args, from, prefix }) {
        const url = args[0];
        const quality = String(args[1] || 'hd').toLowerCase();
        const width = quality === 'fhd' ? 1920 : 1366;
        let awaitMsg = null;

        if (!url.startsWith('http://') && !url.startsWith('https://')) {
            await sock.sendMessage(from, {
                text: `❌ ERROR\nMessage: Invalid URL\n\n💡 Usage: ${prefix}screenshot <valid-url>\n📝 Example: ${prefix}screenshot https://google.com`
            }, { quoted: message });
            return;
        }

        try {
            // React with loading
            await sock.sendMessage(from, {
                react: {
                    text: '⏳',
                    key: message.key
                }
            });

            // Send awaiting message
            const awaitText = '🔄 Generating screenshot...';
            awaitMsg = await sock.sendMessage(from, { text: awaitText }, { quoted: message });

            // Primary source (HD static screenshot)
            const primary = `https://image.thum.io/get/fullpage/noanimate/width/${width}/${encodeURIComponent(url)}`;
            let response;
            try {
                response = await axios.get(primary, { responseType: 'arraybuffer', timeout: 65000 });
            } catch {
                const fallback = `https://kaiz-apis.gleeze.com/api/screenshot?url=${encodeURIComponent(url)}&apikey=a0ebe80e-bf1a-4dbf-8d36-6935b1bfa5ea`;
                response = await axios.get(fallback, { responseType: 'arraybuffer', timeout: 60000 });
            }

            const imageBuffer = Buffer.from(response.data, 'binary');

            // Send screenshot
            await sock.sendMessage(from, {
                image: imageBuffer,
                caption: `📸 Screenshot (${quality.toUpperCase()})\n${url}\n\n💫 Generated by ${config.botName}`
            }, { quoted: message });

            // Delete awaiting message
            await sock.sendMessage(from, { delete: awaitMsg.key });

        } catch (error) {
            console.error('Screenshot error:', error);
            await sock.sendMessage(from, {
                text: `❌ ERROR\nMessage: Failed to generate screenshot\n\n⚠️ Error: ${error.message}\n🔄 Try again later`
            }, { quoted: message });

            // Delete awaiting message if exists
            try {
                if (awaitMsg?.key) await sock.sendMessage(from, { delete: awaitMsg.key });
            } catch (deleteError) {
                console.error('Failed to delete awaiting message:', deleteError);
            }
        }
    }
};
